version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # RabbitMQ protocol
      - "15672:15672"     # RabbitMQ Management UI

  user_service:
    build: ./user_service
    container_name: user_service
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@postgres:5432/user_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      RABBITMQ_HOST: rabbitmq

    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  notification_service:
    build: ./notification_service
    container_name: notification_service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      RABBITMQ_HOST: rabbitmq
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: Test@gmail.com
      SMTP_PASSWORD: Test_App_Password
      EMAIL_FROM: saisri@gmail.com
    ports:
    - "8001:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: